debug: false
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mariadb://localhost:3306/kladionica_java
    username: root
    password: marko
    initialization: true


#logging:
#  level:
#    org.springframework.jdbc.core: TRACE



  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:

    static-locations: classpath:/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/



#
server:
  port: '9910'
file:
  upload-dir: src/main/resources/static/

app:
  timeReviewMaxbet: 12
  timeReviewMozzart: 3
  addressMaxBet: 'https://www.maxbet.rs/ibet-web-client/#/home#top'
  addressForeign: 'https://www.orbitxch.com/customer/inplay/highlights?search='
  addressMozzart: 'https://www.mozzartbet.com/sr/kladjenje-2018#/?sid=1'
  stakeForCalculation: 100
  timeRefreshMatches: 360
  timeRefreshQuotas: 5
  minimumQuota: 1.5
  minimumPayment: 50
  minimumProfit: 3.5
  host: 'mail.lumenspei.com'
  username: 'marko.milosevic@lumenspei.com'
  password: 'Donjev.018'



