debug: false
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mariadb://localhost:3306/kladionica_java
    username: root
    password: marko
    initialization: true






  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: create


  mvc:

    static-locations: classpath:/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/



#
server:
  port: '9910'
file:
  upload-dir: src/main/resources/static/

app:
  timeReview: 3
  addressMaxBet: 'https://www.maxbet.rs/ibet-web-client/#/home#top'
  addressForeign: 'https://www.orbitxch.com/customer/inplay/highlights?search='
  bet: 100
  timeRefreshMatches: 120
  timeRefreshQuotas: 10


